### ISSUE TITLE
name modules coherently with MNE

### ISSUE THREAD

**Issue by dengemann** [JoseAlanis/mne-stats#1]
visualization.py -> viz.py

Also make stats.py module and utils.py if needed.

**Comment by jona-sassenhagen** [comment]
Similarly, group_analysis -> group sounds more MNE-y right?

**Comment by dengemann** [comment]
well let’s distinguish examples from modules. It could be a script “plot_group_analysis”

**Comment by JoseAlanis** [comment]
ok, good point, I'll keep the moduls consitent with MNE. "plot_group_analysis" sounds good, we can start with an example and then see from there.
